#!/usr/bin/env bash

set -eu

cd "$(dirname "$0")/.."

function clone_repo {
	owner=$1
	name=$2
	sha=$3

	path=examples/$name
	if [ ! -d "$path" ]; then
		echo "Cloning $owner/$name"
		git clone "https://github.com/$owner/$name" "$path"
	fi

	pushd "$path" >/dev/null
	actual_sha=$(git rev-parse HEAD)
	if [ "$actual_sha" != "$sha" ]; then
		echo "Updating $owner/$name to $sha"
		git fetch
		git reset --hard "$sha"
	fi
	popd >/dev/null
}

clone_repo apache thrift f223bd3b54d04c21289d806c7f51b115757703e7
clone_repo facebook fbthrift eb94c737bc4b0624aac8a91f7a2d2833ef9b1c90
clone_repo twitter scrooge 39542d5bcd0d35a6957cb0c8ab2a2dc8d3180636
clone_repo line armeria 9e7d453d58f90fe7340b327a7cef684a4ea92afe
clone_repo cloudwego pilota 0ad25f1a9420cc68e4546c4cf7a0fb2f8158858c
clone_repo jaegertracing jaeger-idl 05fe64e9c305526901f70ff692030b388787e388
clone_repo stripe-archive herringbone 4f0524287ef47fc897702d654572bbeee1004879
clone_repo Workiva frugal fd26f827057ff45d08a7ffccecea64d9f3d4d4c1

known_failures="$(cat script/known_failures.txt)"

# shellcheck disable=2046
tree-sitter parse -q \
	"examples/**/*.thrift" \
	$(for file in $known_failures; do echo "!${file}"; done)

example_count=$(find examples -name "*.thrift" | wc -l)
failure_count=$(wc -w <<<"$known_failures")
success_count=$((example_count - failure_count))
success_percent=$(bc -l <<<"100*${success_count}/${example_count}")

printf \
	"Successfully parsed %d of %d example files (%.1f%%)\n" \
	$success_count "$example_count" "$success_percent"
